name: firesbase_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  another_flushbar: ^1.12.30
  cloud_firestore: ^4.14.0
  dio: ^5.4.2+1
  equatable: ^2.0.5
  firebase_auth: 4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  fluttertoast: ^8.2.4
  fvm: ^2.4.1
  get_it: ^7.6.7
  image_picker: ^1.0.7
  qr_flutter: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
