// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKmTLQen_NJgXeboin4pnHUMS0gN_DZRc',
    appId: '1:1007302827188:web:0b8599c15e0f2815558be1',
    messagingSenderId: '1007302827188',
    projectId: 'product-list-test-99210',
    authDomain: 'product-list-test-99210.firebaseapp.com',
    storageBucket: 'product-list-test-99210.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCchvu4jWRyLMzEo3wV2B-9tztHdy5_rr0',
    appId: '1:1007302827188:android:0783448e6ec281e8558be1',
    messagingSenderId: '1007302827188',
    projectId: 'product-list-test-99210',
    storageBucket: 'product-list-test-99210.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGK1FA_7ZEJMMEOpdVNManTjCids_vL44',
    appId: '1:1007302827188:ios:2c7d35a02e92a046558be1',
    messagingSenderId: '1007302827188',
    projectId: 'product-list-test-99210',
    storageBucket: 'product-list-test-99210.appspot.com',
    iosBundleId: 'com.example.firesbaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGK1FA_7ZEJMMEOpdVNManTjCids_vL44',
    appId: '1:1007302827188:ios:9cbb452201f1dc28558be1',
    messagingSenderId: '1007302827188',
    projectId: 'product-list-test-99210',
    storageBucket: 'product-list-test-99210.appspot.com',
    iosBundleId: 'com.example.firesbaseTest.RunnerTests',
  );
}
